name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install vsce (Visual Studio Code Extension Manager)
      run: npm install -g vsce

    - name: Install dependencies
      run: npm ci

    - name: Package and publish extension
      run: vsce publish --pat ${{ secrets.VSCE_TOKEN }}
      env:
        NODE_ENV: production
